#!/bin/bash
echo user passed $withUser - password $withPassword
export ENV_USER=${withUser:-sae}
export ENV_PASSWORD=${withPassword:-$ENV_USER}

/usr/bin/containersshserver-setup.sh

service ssh start
/bin/bash

