#!/bin/bash
#echo user passed $withUser - password $withPassword

export ENV_USER=${withUser:-sae}
export ENV_PASSWORD=${withPassword:-$ENV_USER}

export ENV_TZ=${TimeZone:-Europe/Madrid}

ln -snf $(echo "/usr/share/zoneinfo/$ENV_TZ") /etc/localtime && echo "$ENV_TZ" > /etc/timezone
echo timezone $ENV_TZ set to $(cat /etc/timezone)

echo setting up the ssh server
/usr/bin/containersshserver-setup.sh

echo starting ssh server
service ssh start

echo launching endless command
echo $(ls /bin/w*)
#/bin/sh
#/bin/watch "ls /tmp"
/usr/bin/bootstrap.sh
